version: '2'
services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "5000:5000"

  db:
    image: "postgres:9-alpine"
    environment:
      - POSTGRES_DB=tabkeeper
      - POSTGRES_PASSWORD_FILE=/secret
    volumes:
     - ${PWD}/secret:/secret:ro
